/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as CurationRouteImport } from './routes/curation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesIndexRouteImport } from './routes/series/index'
import { Route as ConceptsIndexRouteImport } from './routes/concepts/index'
import { Route as AuthorsIndexRouteImport } from './routes/authors/index'
import { Route as WorksWorkIdRouteImport } from './routes/works.$workId'
import { Route as SeriesSeriesIdRouteImport } from './routes/series.$seriesId'
import { Route as ConceptsConceptIdRouteImport } from './routes/concepts.$conceptId'
import { Route as AuthorsAuthorIdRouteImport } from './routes/authors.$authorId'
import { Route as ApiConceptsRouteImport } from './routes/api/concepts'
import { Route as ApiAuthorsOpenlibraryRouteImport } from './routes/api/authors/openlibrary'

const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const CurationRoute = CurationRouteImport.update({
  id: '/curation',
  path: '/curation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsIndexRoute = ConceptsIndexRouteImport.update({
  id: '/concepts/',
  path: '/concepts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsIndexRoute = AuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksWorkIdRoute = WorksWorkIdRouteImport.update({
  id: '/works/$workId',
  path: '/works/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSeriesIdRoute = SeriesSeriesIdRouteImport.update({
  id: '/series/$seriesId',
  path: '/series/$seriesId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsConceptIdRoute = ConceptsConceptIdRouteImport.update({
  id: '/concepts/$conceptId',
  path: '/concepts/$conceptId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsAuthorIdRoute = AuthorsAuthorIdRouteImport.update({
  id: '/authors/$authorId',
  path: '/authors/$authorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConceptsRoute = ApiConceptsRouteImport.update({
  id: '/api/concepts',
  path: '/api/concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthorsOpenlibraryRoute = ApiAuthorsOpenlibraryRouteImport.update({
  id: '/api/authors/openlibrary',
  path: '/api/authors/openlibrary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/curation': typeof CurationRoute
  '/ingest': typeof IngestRoute
  '/api/concepts': typeof ApiConceptsRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/concepts/$conceptId': typeof ConceptsConceptIdRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/authors/': typeof AuthorsIndexRoute
  '/concepts/': typeof ConceptsIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/api/authors/openlibrary': typeof ApiAuthorsOpenlibraryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/curation': typeof CurationRoute
  '/ingest': typeof IngestRoute
  '/api/concepts': typeof ApiConceptsRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/concepts/$conceptId': typeof ConceptsConceptIdRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/authors': typeof AuthorsIndexRoute
  '/concepts': typeof ConceptsIndexRoute
  '/series': typeof SeriesIndexRoute
  '/api/authors/openlibrary': typeof ApiAuthorsOpenlibraryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/curation': typeof CurationRoute
  '/ingest': typeof IngestRoute
  '/api/concepts': typeof ApiConceptsRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/concepts/$conceptId': typeof ConceptsConceptIdRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/authors/': typeof AuthorsIndexRoute
  '/concepts/': typeof ConceptsIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/api/authors/openlibrary': typeof ApiAuthorsOpenlibraryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/curation'
    | '/ingest'
    | '/api/concepts'
    | '/authors/$authorId'
    | '/concepts/$conceptId'
    | '/series/$seriesId'
    | '/works/$workId'
    | '/authors/'
    | '/concepts/'
    | '/series/'
    | '/api/authors/openlibrary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/curation'
    | '/ingest'
    | '/api/concepts'
    | '/authors/$authorId'
    | '/concepts/$conceptId'
    | '/series/$seriesId'
    | '/works/$workId'
    | '/authors'
    | '/concepts'
    | '/series'
    | '/api/authors/openlibrary'
  id:
    | '__root__'
    | '/'
    | '/curation'
    | '/ingest'
    | '/api/concepts'
    | '/authors/$authorId'
    | '/concepts/$conceptId'
    | '/series/$seriesId'
    | '/works/$workId'
    | '/authors/'
    | '/concepts/'
    | '/series/'
    | '/api/authors/openlibrary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CurationRoute: typeof CurationRoute
  IngestRoute: typeof IngestRoute
  ApiConceptsRoute: typeof ApiConceptsRoute
  AuthorsAuthorIdRoute: typeof AuthorsAuthorIdRoute
  ConceptsConceptIdRoute: typeof ConceptsConceptIdRoute
  SeriesSeriesIdRoute: typeof SeriesSeriesIdRoute
  WorksWorkIdRoute: typeof WorksWorkIdRoute
  AuthorsIndexRoute: typeof AuthorsIndexRoute
  ConceptsIndexRoute: typeof ConceptsIndexRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
  ApiAuthorsOpenlibraryRoute: typeof ApiAuthorsOpenlibraryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curation': {
      id: '/curation'
      path: '/curation'
      fullPath: '/curation'
      preLoaderRoute: typeof CurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/': {
      id: '/concepts/'
      path: '/concepts'
      fullPath: '/concepts/'
      preLoaderRoute: typeof ConceptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/': {
      id: '/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$workId': {
      id: '/works/$workId'
      path: '/works/$workId'
      fullPath: '/works/$workId'
      preLoaderRoute: typeof WorksWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$seriesId': {
      id: '/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof SeriesSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/$conceptId': {
      id: '/concepts/$conceptId'
      path: '/concepts/$conceptId'
      fullPath: '/concepts/$conceptId'
      preLoaderRoute: typeof ConceptsConceptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$authorId': {
      id: '/authors/$authorId'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId'
      preLoaderRoute: typeof AuthorsAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/concepts': {
      id: '/api/concepts'
      path: '/api/concepts'
      fullPath: '/api/concepts'
      preLoaderRoute: typeof ApiConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/authors/openlibrary': {
      id: '/api/authors/openlibrary'
      path: '/api/authors/openlibrary'
      fullPath: '/api/authors/openlibrary'
      preLoaderRoute: typeof ApiAuthorsOpenlibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CurationRoute: CurationRoute,
  IngestRoute: IngestRoute,
  ApiConceptsRoute: ApiConceptsRoute,
  AuthorsAuthorIdRoute: AuthorsAuthorIdRoute,
  ConceptsConceptIdRoute: ConceptsConceptIdRoute,
  SeriesSeriesIdRoute: SeriesSeriesIdRoute,
  WorksWorkIdRoute: WorksWorkIdRoute,
  AuthorsIndexRoute: AuthorsIndexRoute,
  ConceptsIndexRoute: ConceptsIndexRoute,
  SeriesIndexRoute: SeriesIndexRoute,
  ApiAuthorsOpenlibraryRoute: ApiAuthorsOpenlibraryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
