/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesIndexRouteImport } from './routes/series/index'
import { Route as ConceptsIndexRouteImport } from './routes/concepts/index'
import { Route as AuthorsIndexRouteImport } from './routes/authors/index'
import { Route as SeriesSeriesIdRouteImport } from './routes/series.$seriesId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as ConceptsConceptIdRouteImport } from './routes/concepts.$conceptId'
import { Route as AuthorsAuthorIdRouteImport } from './routes/authors.$authorId'
import { Route as ApiConceptsRouteImport } from './routes/api/concepts'
import { Route as ApiAuthorsOpenlibraryRouteImport } from './routes/api/authors/openlibrary'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsIndexRoute = ConceptsIndexRouteImport.update({
  id: '/concepts/',
  path: '/concepts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsIndexRoute = AuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSeriesIdRoute = SeriesSeriesIdRouteImport.update({
  id: '/series/$seriesId',
  path: '/series/$seriesId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsConceptIdRoute = ConceptsConceptIdRouteImport.update({
  id: '/concepts/$conceptId',
  path: '/concepts/$conceptId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsAuthorIdRoute = AuthorsAuthorIdRouteImport.update({
  id: '/authors/$authorId',
  path: '/authors/$authorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConceptsRoute = ApiConceptsRouteImport.update({
  id: '/api/concepts',
  path: '/api/concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthorsOpenlibraryRoute = ApiAuthorsOpenlibraryRouteImport.update({
  id: '/api/authors/openlibrary',
  path: '/api/authors/openlibrary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/concepts': typeof ApiConceptsRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/concepts/$conceptId': typeof ConceptsConceptIdRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/authors/': typeof AuthorsIndexRoute
  '/concepts/': typeof ConceptsIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/api/authors/openlibrary': typeof ApiAuthorsOpenlibraryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/concepts': typeof ApiConceptsRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/concepts/$conceptId': typeof ConceptsConceptIdRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/authors': typeof AuthorsIndexRoute
  '/concepts': typeof ConceptsIndexRoute
  '/series': typeof SeriesIndexRoute
  '/api/authors/openlibrary': typeof ApiAuthorsOpenlibraryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/concepts': typeof ApiConceptsRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/concepts/$conceptId': typeof ConceptsConceptIdRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/authors/': typeof AuthorsIndexRoute
  '/concepts/': typeof ConceptsIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/api/authors/openlibrary': typeof ApiAuthorsOpenlibraryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api/concepts'
    | '/authors/$authorId'
    | '/concepts/$conceptId'
    | '/demo/prisma'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/series/$seriesId'
    | '/authors/'
    | '/concepts/'
    | '/series/'
    | '/api/authors/openlibrary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api/concepts'
    | '/authors/$authorId'
    | '/concepts/$conceptId'
    | '/demo/prisma'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/series/$seriesId'
    | '/authors'
    | '/concepts'
    | '/series'
    | '/api/authors/openlibrary'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api/concepts'
    | '/authors/$authorId'
    | '/concepts/$conceptId'
    | '/demo/prisma'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/series/$seriesId'
    | '/authors/'
    | '/concepts/'
    | '/series/'
    | '/api/authors/openlibrary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiConceptsRoute: typeof ApiConceptsRoute
  AuthorsAuthorIdRoute: typeof AuthorsAuthorIdRoute
  ConceptsConceptIdRoute: typeof ConceptsConceptIdRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  SeriesSeriesIdRoute: typeof SeriesSeriesIdRoute
  AuthorsIndexRoute: typeof AuthorsIndexRoute
  ConceptsIndexRoute: typeof ConceptsIndexRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
  ApiAuthorsOpenlibraryRoute: typeof ApiAuthorsOpenlibraryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/': {
      id: '/concepts/'
      path: '/concepts'
      fullPath: '/concepts/'
      preLoaderRoute: typeof ConceptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/': {
      id: '/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$seriesId': {
      id: '/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof SeriesSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/$conceptId': {
      id: '/concepts/$conceptId'
      path: '/concepts/$conceptId'
      fullPath: '/concepts/$conceptId'
      preLoaderRoute: typeof ConceptsConceptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$authorId': {
      id: '/authors/$authorId'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId'
      preLoaderRoute: typeof AuthorsAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/concepts': {
      id: '/api/concepts'
      path: '/api/concepts'
      fullPath: '/api/concepts'
      preLoaderRoute: typeof ApiConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/authors/openlibrary': {
      id: '/api/authors/openlibrary'
      path: '/api/authors/openlibrary'
      fullPath: '/api/authors/openlibrary'
      preLoaderRoute: typeof ApiAuthorsOpenlibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiConceptsRoute: ApiConceptsRoute,
  AuthorsAuthorIdRoute: AuthorsAuthorIdRoute,
  ConceptsConceptIdRoute: ConceptsConceptIdRoute,
  DemoPrismaRoute: DemoPrismaRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  SeriesSeriesIdRoute: SeriesSeriesIdRoute,
  AuthorsIndexRoute: AuthorsIndexRoute,
  ConceptsIndexRoute: ConceptsIndexRoute,
  SeriesIndexRoute: SeriesIndexRoute,
  ApiAuthorsOpenlibraryRoute: ApiAuthorsOpenlibraryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
