/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConceptsRouteImport } from './routes/concepts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as ApiConceptsRouteImport } from './routes/api/concepts'
import { Route as ApiAuthorsOpenlibraryRouteImport } from './routes/api/authors/openlibrary'

const ConceptsRoute = ConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConceptsRoute = ApiConceptsRouteImport.update({
  id: '/api/concepts',
  path: '/api/concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthorsOpenlibraryRoute = ApiAuthorsOpenlibraryRouteImport.update({
  id: '/api/authors/openlibrary',
  path: '/api/authors/openlibrary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/concepts': typeof ConceptsRoute
  '/api/concepts': typeof ApiConceptsRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/authors/openlibrary': typeof ApiAuthorsOpenlibraryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/concepts': typeof ConceptsRoute
  '/api/concepts': typeof ApiConceptsRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/authors/openlibrary': typeof ApiAuthorsOpenlibraryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/concepts': typeof ConceptsRoute
  '/api/concepts': typeof ApiConceptsRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/authors/openlibrary': typeof ApiAuthorsOpenlibraryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/concepts'
    | '/api/concepts'
    | '/demo/prisma'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/api/authors/openlibrary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/concepts'
    | '/api/concepts'
    | '/demo/prisma'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/api/authors/openlibrary'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/concepts'
    | '/api/concepts'
    | '/demo/prisma'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/api/authors/openlibrary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConceptsRoute: typeof ConceptsRoute
  ApiConceptsRoute: typeof ApiConceptsRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthorsOpenlibraryRoute: typeof ApiAuthorsOpenlibraryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/concepts': {
      id: '/concepts'
      path: '/concepts'
      fullPath: '/concepts'
      preLoaderRoute: typeof ConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/concepts': {
      id: '/api/concepts'
      path: '/api/concepts'
      fullPath: '/api/concepts'
      preLoaderRoute: typeof ApiConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/authors/openlibrary': {
      id: '/api/authors/openlibrary'
      path: '/api/authors/openlibrary'
      fullPath: '/api/authors/openlibrary'
      preLoaderRoute: typeof ApiAuthorsOpenlibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConceptsRoute: ConceptsRoute,
  ApiConceptsRoute: ApiConceptsRoute,
  DemoPrismaRoute: DemoPrismaRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthorsOpenlibraryRoute: ApiAuthorsOpenlibraryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
